# Generated by Django 5.2.7 on 2025-10-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('do', 'Discipline Officer'), ('counselor', 'Guidance Counselor'), ('guidance', 'Guidance Counselor'), ('principal', 'Principal')], max_length=20),
        ),
    ]
