# Generated by Django 5.2.7 on 2025-10-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingsession',
            name='counselor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['counselor', 'guidance']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
