# Generated by Django 5.2.7 on 2025-10-25 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_counselingsession_counselor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingsession',
            name='counselor',
            field=models.ForeignKey(limit_choices_to={'role': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('do', 'Discipline Officer'), ('counselor', 'Guidance Counselor'), ('principal', 'Principal')], max_length=20),
        ),
    ]
