# Generated by Django 5.2.7 on 2025-10-25 17:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_counselingsession_counselor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.curriculum'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.grade'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_date',
            field=models.DateField(default=datetime.date(2025, 10, 25)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_time',
            field=models.TimeField(default=datetime.time(17, 53, 4, 489110)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='involved_students',
            field=models.TextField(blank=True, help_text='Names or IDs of involved students'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.section'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.track'),
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='legal_references',
            field=models.TextField(default='School Policy', help_text='Legal references and documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reported_student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='severity',
            field=models.CharField(choices=[('grave', 'Grave Offense'), ('prohibited', 'Prohibited Act')], max_length=15),
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('grade_level', models.CharField(max_length=10)),
                ('section_name', models.CharField(max_length=100)),
                ('track_code', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('grade_level', 'section_name', 'track_code')},
            },
        ),
    ]
