# Generated by Django 5.2.7 on 2025-10-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentreport_curriculum_incidentreport_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='grade_level',
            field=models.CharField(default='7', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='section_name',
            field=models.CharField(default='Section 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.grade'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.section'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.track'),
        ),
    ]
