# Generated by Django 5.2.7 on 2025-10-25 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incidentreport_grade_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_notes', models.TextField()),
                ('recommendation', models.CharField(choices=[('counseling', 'Counseling Only'), ('sanction', 'Recommend Sanction'), ('monitoring', 'Monitoring Required'), ('resolved', 'Case Resolved')], max_length=20)),
                ('is_repeat_offender', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(limit_choices_to={'role': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_cases', models.ManyToManyField(blank=True, related_name='related_evaluations', to='incidents.incidentreport')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='incidents.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='incidents.incidentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('total_reports', models.IntegerField(default=0)),
                ('minor_violations', models.IntegerField(default=0)),
                ('major_violations', models.IntegerField(default=0)),
                ('resolved_cases', models.IntegerField(default=0)),
                ('pending_cases', models.IntegerField(default=0)),
                ('most_common_violation', models.CharField(blank=True, max_length=200)),
                ('grade_with_most_violations', models.CharField(blank=True, max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=200)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('emergency', 'Emergency')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major')], max_length=10)),
                ('date_occurred', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidentreport')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='violation_history', to=settings.AUTH_USER_MODEL)),
                ('violation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incidenttype')),
            ],
            options={
                'ordering': ['-date_occurred'],
            },
        ),
    ]
