# Generated by Django 4.2 on 2025-10-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_caseevaluation_internalnote_reportanalytics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingsession',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='incidents.incidentreport'),
        ),
    ]
