# Generated by Django 4.2 on 2025-10-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_counselingsession_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('referred_to_teacher', 'Referred to Teacher')], default='scheduled', max_length=20),
        ),
    ]
