# Generated by Django 4.2 on 2025-11-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_alter_counselingsession_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher_name', 'grade_level', 'section_name', 'track_code')},
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.curriculum'),
        ),
    ]
