# Generated by Django 4.2 on 2025-11-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_add_verdict_to_case_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='evidence_notes',
            field=models.TextField(blank=True, help_text='Notes about evidence status'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='evidence_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('clear', 'Clear - Sufficient Evidence'), ('insufficient', 'Needs More Evidence')], default='pending', max_length=20),
        ),
    ]
