# Generated by Django 4.2 on 2025-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_incidentreport_evidence_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notes about routing decision'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='severity',
            field=models.CharField(choices=[('minor', 'Handle by DO'), ('major', 'Send to Guidance Counselor')], help_text='Routing decision: DO or Counselor', max_length=10),
        ),
    ]
