# Generated by Django 4.2 on 2025-11-23 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_alter_classification_internal_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPFCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_level', models.CharField(help_text='1st, 2nd, or 3rd Commission', max_length=10)),
                ('intervention', models.CharField(help_text='Selected intervention type', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Schedule'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('do', 'Discipline Officer'), ('counselor', 'Guidance Counselor'), ('principal', 'Principal'), ('esp_teacher', 'ESP Teacher/VPF Coordinator')], max_length=20),
        ),
        migrations.CreateModel(
            name='VPFSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor_assigned', models.ForeignKey(blank=True, help_text='VPF Counselor assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.counselor')),
                ('esp_teacher', models.ForeignKey(limit_choices_to={'role': 'esp_teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpf_schedules_managed', to=settings.AUTH_USER_MODEL)),
                ('vpf_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='incidents.vpfcase')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='vpfcase',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpf_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vpfcase',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpf_cases', to='incidents.incidentreport'),
        ),
        migrations.AddField(
            model_name='vpfcase',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='vpf_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
