# Generated by Django 4.2 on 2025-11-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_alter_caseevaluation_evaluation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpfcase',
            name='esp_teacher_assigned',
            field=models.ForeignKey(blank=True, help_text='ESP Teacher/VPF Counselor assigned to this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpf_cases_assigned', to='incidents.counselor'),
        ),
    ]
