# Generated by Django 4.2 on 2025-11-24 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_vpfcase_esp_teacher_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpfcase',
            name='esp_teacher_assigned',
            field=models.ForeignKey(blank=True, help_text='ESP Teacher assigned to this case', limit_choices_to={'role': 'esp_teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpf_cases_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
