# Generated by Django 4.2 on 2025-11-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_alter_vpfcase_esp_teacher_assigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenttype',
            options={'ordering': ['severity', 'name']},
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='severity',
            field=models.CharField(choices=[('prohibited', 'Prohibited Acts'), ('school_policy', 'Other School Policies')], max_length=20),
        ),
    ]
