# Generated by Django 4.2 on 2025-11-25 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0020_alter_incidenttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_schedules_managed', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_schedules', to='incidents.caseevaluation')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_schedule_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
