# Generated by Django 4.2 on 2025-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_counselingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender of the involved student', max_length=10),
        ),
    ]
