# Generated by Django 4.2 on 2025-11-27 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0022_incidentreport_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('parent_conference', 'Parent Conference'), ('interview', 'Interview'), ('follow_up', 'Follow-up Meeting')], default='parent_conference', max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='Discipline Office', max_length=200)),
                ('attendees', models.TextField(blank=True, help_text='Names of attendees (parents, guardians, etc.)')),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the meeting')),
                ('notes', models.TextField(blank=True, help_text='Meeting notes or outcomes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline_officer', models.ForeignKey(limit_choices_to={'role': 'do'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='do_schedules_managed', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_schedules', to='incidents.incidentreport')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_schedule_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
