# Generated by Django 4.2 on 2025-11-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0023_doschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevaluation',
            name='recommendation',
            field=models.CharField(choices=[('counseling', 'Counseling Only'), ('monitoring', 'Monitoring Required'), ('resolved', 'Case Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('do', 'Discipline Officer'), ('counselor', 'Guidance Counselor'), ('esp_teacher', 'ESP Teacher/VPF Coordinator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('classified', 'Classified'), ('evaluated', 'Evaluated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Sanction',
        ),
    ]
