# Generated by Django 4.2.16 on 2025-11-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0024_remove_sanction_and_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='bullying_type',
            field=models.CharField(blank=True, help_text='Type of bullying if incident_type is bullying', max_length=50, null=True),
        ),
    ]
