# Generated by Django 4.2.16 on 2025-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0025_incidentreport_bullying_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Optional middle name', max_length=150, null=True),
        ),
    ]
