# Generated by Django 4.2.16 on 2025-12-02 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0026_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Mark as confidential (recommended for teacher incidents)'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_is_victim',
            field=models.BooleanField(default=False, help_text='Check if reporter is also a victim/involved party'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_submitted', 'Report Submitted'), ('party_confirmed', 'Party Confirmed'), ('do_classified', 'DO Classified'), ('guidance_evaluation', 'Guidance Evaluation'), ('vrf_assigned', 'VRF Assigned'), ('counseling_scheduled', 'Counseling Scheduled'), ('session_completed', 'Session Completed'), ('status_update', 'Status Update')], default='status_update', max_length=50),
        ),
        migrations.CreateModel(
            name='InvolvedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('grade_level', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_level_taught', models.CharField(blank=True, max_length=50, null=True)),
                ('name_if_unknown', models.CharField(blank=True, help_text='Name if party not in system', max_length=200, null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Confirmed by DO')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_involved_parties', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_parties', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.curriculum')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.section')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_involved_parties', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_involved_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Involved Party',
                'verbose_name_plural': 'Involved Parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='involved_parties',
            field=models.ManyToManyField(blank=True, help_text='Students or teachers involved in this incident', related_name='incident_reports', to='incidents.involvedparty'),
        ),
    ]
